### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by bachirelkhadir** [sleuth-io/code-video-generator#1]
Really nice repo you have here! I gave it try on Ubuntu 20.10:
```
wget https://raw.githubusercontent.com/sleuth-io/code-video-generator/master/bin/codevidgen.sh && c
hmod 755 codevidgen.sh
./codevidgen.sh simple.py -ql
```
but I get the following error log below. Any ideas on how to fix this?

```
Output will be stored in 'media'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pangocffi 0.8.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('pangocffi<0.7.0,>=0.6.0'), {'manimce'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/codevidgen", line 33, in <module>
    sys.exit(load_entry_point('code-video-generator', 'console_scripts', 'codevidgen')())
  File "/app/code_video_cli/__init__.py", line 16, in main
    from manim.__main__ import main as manim_main
  File "/usr/local/lib/python3.8/site-packages/manim/__init__.py", line 48, in <module>
    from .mobject.svg.code_mobject import *
  File "/usr/local/lib/python3.8/site-packages/manim/mobject/svg/code_mobject.py", line 27, in <module>
    class Code(VGroup):
  File "/usr/local/lib/python3.8/site-packages/manim/mobject/svg/code_mobject.py", line 133, in Code
    styles_list = list(get_all_styles())
  File "/usr/local/lib/python3.8/site-packages/pygments/styles/__init__.py", line 85, in get_all_styles
    for name, _ in find_plugin_styles():
  File "/usr/local/lib/python3.8/site-packages/pygments/plugin.py", line 64, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "/usr/local/lib/python3.8/site-packages/pygments/plugin.py", line 46, in iter_entry_points
    import pkg_resources
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pangocffi 0.8.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('pangocffi<0.7.0,>=0.6.0'), {'manimce'})
```

**Comment by mrdon** [comment]
Try it now, though you'll need to re-download the codevidgen.sh script

**Comment by mrdon** [comment]
Oh, and thanks for the report!

**Comment by bachirelkhadir** [comment]
Fantastic, thank you!
