### ISSUE TITLE
Incompatible with latest version of manim

### ISSUE THREAD

**Issue by crdoconnor** [sleuth-io/code-video-generator#6]
This is the error:

```
Manim Community v0.17.3

Traceback (most recent call last):
  File "/src/hitch/video.py", line 1, in <module>
    from examples.boxes import BoxesScene
  File "/src/hitch/examples/boxes.py", line 8, in <module>
    from code_video import Connection
  File "/gen/venv/lib/python3.11/site-packages/code_video/__init__.py", line 5, in <module>
    from .sequence import Actor  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gen/venv/lib/python3.11/site-packages/code_video/sequence.py", line 22, in <module>
    from manim.mobject.geometry import DEFAULT_DASH_LENGTH
ImportError: cannot import name 'DEFAULT_DASH_LENGTH' from 'manim.mobject.geometry' (/gen/venv/lib/python3.11/site-packages/manim/mobject/geometry/__init__.py)
```

**Comment by dejavu1987** [comment]
Not just latest, the latest Manim supported seems to be 0.11.0
